package com.rumanski.ordering;

public enum OrderStatus {

	CREATED, RESERVED, PAID, PICKED, SHIPPED, COMPLETED,

	SHIPPING_CANCELED, PICKING_CANCELED, PAYMENT_CANCELED, RESERVATION_CANCELED, CANCELED;

}
